FROM nginx:latest

# Remove the default Nginx welcome page
RUN rm /usr/share/nginx/html/*

# Create a custom Nginx configuration
COPY my_nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port Nginx will listen on
EXPOSE 40301
